version: '3'
services:
#Service odoo toma el Dockerfile de ./build/odoo13
 odoo:
  build: ./odoo
  hostname: odoo
  env_file: 
  - "odoo/envfile"
  #Mapea el 8069 del container al anfitrión
  ports:
  - "8069:8069"
#Service postgres
 postgres:
  build: ./postgres
  hostname: postgres
  env_file:  
  - "odoo/envfile"
  ports:
  - "5432:5432"
  volumes:
  - pg_data:/var/lib/postgresql/11/main
volumes:
  pg_data:
